var flavors = [
  "Only a few days left to make a tax-deductable contribution to keep your node_modules huge. Please help pay our bills.",
  "Take me to flavortown!",
  "Short of screaming-hot Thai food, everything can be suitable for kids too.",
  "Cooking is like snow skiing: If you don't fall at least 10 times, then you're not skiing hard enough.",
  "Cooking with kids is not just about ingredients, recipes, and cooking. It's about harnessing imagination, empowerment, and creativity.",
  "I was always a kid trying to make a buck. I borrowed a dollar from my dad, went to the penny candy store, bought a dollar's worth of candy, set up my booth, and sold candy for five cents apiece. Ate half my inventory, made $2.50, gave my dad back his dollar.",
  "There are two different things: there's grilling, and there's barbecue. Grilling is when people say, 'We're going to turn up the heat, make it really hot and sear a steak, sear a burger, cook a chicken.' Barbecue is going low and slow.",
  "I love 'Iron Chef' and I love 'Chopped.' I watch both of them. I think it is crazy what those chefs go through.",
  "Growing up in Northern California, I've only seen snow at Christmas maybe twice in my life! I was always jealous of my cousins on the East Coast with their white Christmases.",
  "I once saw professional soccer up there in Seattle, the Sounders. I went and saw that. I'm not a big soccer fan, but watching a live game is unbelievable. And then I went to Italy and saw a soccer match; it's something everyone should do once. It'll blow your mind.",
  "Some people are just born to cook and talk.",
  "In Japanese, sushi does not mean raw fish. It means seasoned rice.",
  "I'm a five-seasons griller! Did you know I added a new season? Living in Cali, I'm cooking in the yard all the time. I don't care what the weather is like. My hair is impervious to any kind of dampness, so I don't have too much to worry about.",
  "I can't bake anything. I'm the worst. My cakes always come out flat.",
  "Your classic guacamole is just avocados, lime juice, and salt.",
  "I'm not a religious person by any means.",
  "There are races and then there are races. And without a doubt, the Indy 500 is the race that I've always wanted to attend. And now, to be driving the Corvette Pace Car... this is going to be unbelievable.",
  "No matter how tough the meat may be, it's going to be tender if you slice it thin enough.",
  "There's nothing that can replicate the smoky flavor of char, so when I've got the hankering for it, I tell my wife that I'm taking care of dinner. I have three different types of barbecues - a coal, gas and smoker - so I can experiment a lot.",
  "If you slow it down, eat in courses, your body, mind, stomach will catch up with this full feeling and you won't eat as much.",
  "Preparing food is one of life's great joys, but a lot of times, parents ask their kids if they want to cook with them and then tell them to go peel a bag of potatoes. That's not cooking - that's working!",
  "If you're cooking and not making mistakes, you're not playing outside your safety zone. I don't expect it all to be good. I have fat dogs because I scrap that stuff out the back door.",
  "It's always good to go over the recipe beforehand, so you can easily think of the next thing that needs to be done.",
  "I think anyone that grew up in the '70s and '80s grew up with Bob Barker and Wink Martindale and I think that was just always... when you were a game show host, you were the man of the hour.",
  "My restaurant, Tex Wasabi's, we have a whole 'Minute to Win It' challenge going on on Sundays already. The show hasn't even aired and they're already doing challenges where people are coming and participating. I think it's going to take over.",
  "Kids want to saute, to cut the pizza, to see how the ingredients come together. If you let them do the fun stuff, they'll develop skills and interests that will stay with them forever.",
  "You don't have to eat a whole cheeseburger, just take a piece of the cheeseburger.",
  "Liver is my number one most hated food. Oh, God, I get sick talking about it!",
  "I'm a big fan of doing 'Triple D.' But I don't want to do it forever, don't get me wrong! Travel away from my family, are you crazy? But do you know what it does for these mom-and-pop restaurant joints? It changes their lives forever. I mean, their businesses will never be the same.",
  "I don't know what singers feel like when they make a song and people clap along and love it, but when people walk up to me and say the food was outstanding, that's what it is all about. I cook because I like to make people happy.",
  "My stay-married secret would probably be exercising good communication, not when you have to but all the time. I think if you do that, you kinda just cleanse the situations, so there's not build up. I think that's probably the best way to do it.",
  "Cooking is all about people. Food is maybe the only universal thing that really has the power to bring everyone together. No matter what culture, everywhere around the world, people get together to eat.",
  "What you see is what you get with me. There's no show.",
  "I'm gonna open a small restaurant on the beach in Mexico. We're only gonna have a few tables, and we're only gonna cook what's fresh that day. We're gonna get back to the basics.",
  "I'm not a greasy food guy. I don't eat like that.",
  "There's been quite a few conversations between me and my wife; she'd like to see my hair brown again. So who knows what will happen.",
  "I'm not doing anything for anybody. I'm doing what I do.",
  "The wok is one of my favorite things to work with when I'm camping. Outdoor cooking is not just about hot dogs and hamburgers. There are so many styles of food you can make.",
  "My parents were all into macrobiotic cooking and natural cooking, and my sister was a vegetarian. I wasn't down with that.",
  "I'm not a celebrity chef. I'm a chef that happens to have television shows and a chef that happens to do media.",
  "Get off the beaten path... If you want to find those mom-and-pop joints, those funky little places, just ask around.",
  "Anybody that pays attention to hate really is wasting their time. I don't subscribe. I don't buy in.",
  "If you've really got a problem with me, and you came and told me you had a problem with me, I'd be interested to listen to you. But if you're just some loser that sits there and hammers away on some blog form or whatever, I don't have time for that. Why even worry about it?",
  "I was raised with hippie parents, so I get down with the positive. I don't pay attention to the negative.",
  "I always tell my family - and they laugh about it - but someday, I will write a vegetarian book. My cousin, who's a big vegetarian, tells me flat out, 'You're my favorite vegetarian chef.'",
  "At first, people think about vegetarian food like, 'Here's some veggies. Here's some pasta.' But there's so much more you can do in the vegetarian and vegan world.",
  "I eat healthier than you think. I eat grains and vegetables when I'm home - and I eat in courses. My wife, Lori, thinks it's because I don't want foods to touch. That's not it. If you eat courses, you slow down your meal and eat less. It's a trick I picked up in France as a kid.",
  "My parents moved out to California in 1968 from Ohio in a VW station wagon pulling a little trailer. I was 4 months old. They were following the energy out here.",
  "When I was 12, we began hosting exchange students from Norway, Sweden, Japan and Spain. I soon realized there was a whole world out there. I was determined to spend my sophomore year in high school abroad. My school taught only Spanish, but I wanted to go to France, and I did.",
  "My spiked hair goes back about 15 years ago. I had long, curly rocker hair then. The woman who cuts my hair thought I needed a new style, so I let her surprise me. I flipped when I first saw it, but I soon realized the look was really me. I've always been a little crazy.",
  "I tell anyone who will listen to me: On a cruise, you can be with all these people, or you can be by yourself. You can find tranquility, you can find party, you can find new friends. I'm a cruise convert.",
  "I have my own boat, but when I first thought about taking a cruise, I thought, 'You're going to trap me on a boat, and I'm going to walk in circles and go crazy,' but it's awesome.",
  "I love to exercise. I'm a big hiker, and I like boxing. I mean, I love a good burger, but I keep things in moderation.",
  "After a show, people say, 'I bet you want to just sit back and relax.' No way. First thing I want to do when I'm home is cook.",
  "You have to be confident in who you are and what you're doing. Of course, you try to evolve. I would never tell you, 'Today is the best I will ever be.' I'm always trying to be a better chef, a better dad, a better person.",
  "I love to cook for people. It's my honor, honestly. It's what I have to give.",
  "I'm a big greens fan. I'm a big vegetable fan. I'm a big whole grains fan. And I exercise a lot. That's how I keep this petite dancer's figure.",
  "Everybody has their role in the food world and what they choose to appreciate. I'm not a fine dining chef. I appreciate it. I think Thomas Keller is amazing. But I really like where I'm at; I like what I do. I like how it makes people feel.",
  "I say to folks all the time, 'Watch what you're eating. You don't have to eat it all. Make conscious choices. It doesn't mean you have to starve yourself and eat carrots all day.' Have an awareness.",
  "It's football all day on Sunday. I wish we had football every day; that would make me way happier. Why can't we have that? You've got all these teams! Why can't we just play a Monday game, a Tuesday game, a Wednesday game?",
  "One of the greatest birds I've ever had is called a 'Turducken.' A chicken inside of a duck inside of a turkey. That's one that I love. I've done it a couple times.",
  "We're getting ready to sit down at the table and have Thanksgiving, and there's people that are not with their families. There are people that are in dangerous areas, putting their lives on the line to keep our country free, and I think that's something we should all celebrate every day.",
  "I'm not an actor. Lord knows, I'd be acting if I were an actor. What you see is what you get.",
  "I am the worst at the grocery store. It turns into three carts. It turns into, 'Oh did you see the truffle cheese? We've got to get the truffle cheese!'",
  "I've been using the same hair wax for as long as I can remember. I'm not a gel guy, I'm not a perfume guy, not really into any of that.",
  "I have three wood-fired ovens... I have one at my house, one at my ranch, one on the trailer that I use for charity events.",
  "The last thing I'm gonna do is, 'This is dynamite!' That's not my gig, man. I love the mom-and-pop joints. I love giving them recognition, but I'm not gonna blow smoke. We walked out of locations; we've changed locations.",
  "I did a big thing with Ritz Crackers - great cracker. Am I now the Ritz chef? No! Do I think the cracker has a lot of diversity and appeal? Yeah! Does it mean that's my foundation of cooking? No!",
  "I take everything very seriously, but I also take it lighthearted to recognize that you can't control it.",
  "My sister and I cooked a lot together; my sister was a very healthy vegetarian. She was always a real good teacher for me about organics, recycling, composting -whenever you hear me talk about it, it's usually because of my sister's influence.",
  "There are three people you need in life: an accountant, a fishmonger, and a bail bondsman.",
  "Triple D is all about three things: Food, story and character.",
  "I need to stay disciplined on the road. Too much food can wreck your palate.",
  "I've always been an eccentric, a rocker at heart. I can't play the guitar, but I can play the griddle.",
  "I am just a regular dude who happened to make it. That's all I am, man. Maybe I was preparing myself in some lifetime to become this person, but I never thought I'd have every rocket shooting off at one time.",
  "If you are AC/DC, you don't get credit for slow songs. And if you are doing a show about food with a blond dude with crazy blond hair and tattoos who drives a hot rod, of course everyone is going to think everything you eat is deep-fried.",
  "I respect anybody that cooks. I know how hard it is.",
  "I have a fond appreciation for the Canadian culture and the Canadian food scene in general.",
  "We are not blessed with junk food - my family and my kids do not eat fast foods.",
  "I was raised not so much in a puritan environment, but for the most part, a pretty healthy one.",
  "My first words were always about food - I grew up in northern California, and when I was 10 years old, I had my own pretzel cart business.",
  "When I was 13, I opened my own business called The Awesome Pretzel Company, and my dad helped me build a pretzel cart.",
  "I wake up in the morning thinking about food.",
  "I never knew I would go this far, but I was told by people it wouldn't happen, and now I own four restaurants, and I have one of the best shows on the Food Network. I'm living in the Super Bowl of food.",
  "Food is not just eating energy. It's an experience.",
  "The Tom Brady sandwich would be a prosciutto with a nice Buffalo mozzarella, on a crispy baguette with a little fresh basil. Brady is classy; he's a really cool dude. He's got a lot of flavor.",
  "You can find tranquility, you can find party, you can find new friends. I'm a cruise convert.",
  "No one likes rubbery chicken.",
  "Manage the heat, let the meat cook, and you'll get fantastic results.",
  "Ripe avocados should be soft, not squishy, and you should be able to flick the little stem off easily.",
  "Avocados that haven't fully ripened will lack the big flavor you want for your dip.",
  "Nothing, not even an avocado pit, keeps guacamole green for too long once it's made.",
  "It's OK to make mistakes... Try different things.",
  "People need to take a little bit more risk.",
  "I look at a basketball laying on the ground, and it makes me think of something. Popcorn ball. How 'bout a spicy popcorn ball? That is how my mind is always working.",
  "I get influence from everybody and everything.",
  "Food is a common denominator for all people.",
  "Kids love food. It's about putting materials out there that get kids thinking about food - to get kids interacting about food. It's about simple things, like kids thinking about pasta - getting kids to work with food.",
  "It's a life lesson they need to have, a skill everybody needs - to cook.",
  "College students want good eats. They want it to not be super-expensive, but you've got to be eclectic, you've got to have style, and you've got to make real food.",
  "Contrary to popular belief, I eat all types of food. Fried food is my least favorite.",
  "With messy food, or foods with a lot of sauce, you do 'The Hunch.' I learned it in Philly, watching the dudes in suits eat cheesesteaks. You keep your elbows above your hands because if you don't, the grease runs down your sleeve to your elbow.",
  "If you looked in my fridge, you'd see maybe 12 different mustards.",
  "If it tastes really good, and it's funky, it's funkalicous. If the guy making it is funky, he's funkintacious.",
  "I have the best agents in the world.",
  "'Triple D' is not going anywhere. I enjoy highlighting my brothers and sisters in the business.",
  "I'm a stocky 210 pounds.",
  "I never try and do the same show, ever. The audience controls the dynamic of the shows. Sometimes they listen, and sometimes they ask a million questions.",
  "The wok is one of my favorite things to work with when I'm camping.",
  "Outdoor cooking is not just about hot dogs and hamburgers. There are so many styles of food you can make.",
  "I'm a collector, so I've got all kinds of sunglasses. I'd say I've got about a buck ten, buck twenty.",
  "I'm in a very unique position in that I got to participate in the Food Network by contest. That's long gone, being voted on, but I don't forget where it came from, and I don't forget the people who worked to put me here.",
  "What do people want? Contact. People want to be able to see you and touch you. Are you real?",
  "The No. 1 thing I hear from people when I meet them in the airport is, 'Oh my gosh, you're just like you are on TV.' Well, I'm not an actor. I don't think anyone could figure out how to be this weird.",
  "I've never been an apron fan; it's all too cumbersome to me.",
  "I'm a big eater in terms that l love flavor, but I don't like to eat a lot of one thing. I like to eat a little bit.",
  "I'm a huge kale fan.",
  "I don't eat sweets. I'm not a big dessert guy.",
  "I don't drink soda.",
  "I specifically left the corporate world so I could wear T-shirts, blue jeans, and honestly, I always wanted to be my own boss.",
  "Did I ever think about TV stardom? I don't watch a lot of TV. I wasn't even aware of the phenomenon of what was going on in food television, what you started with the Food Network.",
  "The opportunity to be a star chef, to imagine it would be here in Las Vegas, I couldn't comprehend it.",
  "I really believe you've gotta put the power in the people. They're the ones who are gonna make the experience.",
  "I always wish for more time at home or at the restaurants or on the shows.",
  "I'm a chef, I own restaurants, and there's a behavior in the kitchen you have to have.",
  "Why can't we have a concert with food? Your typical cooking demonstration, there's just no enthusiasm. There's no energy behind it. I said, 'What if we take a cooking demonstration and fortify it with a lot of good music? ... Drive it to the next level?'",
  "I definitely eat in moderation and exercise.",
  "I think there's a misconception that I eat everything. The one or two bites that you see me take, that's it.",
  "When you love the competition, the opportunity to achieve at simple but challenging games, some people are really into it, and I'm one of them.",
  "Howie Mandel is the real deal.",
  "Whenever you get to change somebody's life or watch it and see it happen, it's amazing.",
  "I'm a culinary gangsta with a very spiritual side, so when I was introduced to the 'spiritual gangster' line, I had to have it.",
  "I try to hike at least three times a week when I'm home in Sonoma County.",
  "I was even more of a Hagar fan when he was just Hagar and not Van Hagar.",
  "I wanted to work in corporate restaurants.",
  "It's tough, you know: I'm a chef first, and a restaurant owner, way before I was ever on Food Network, and it's a tough business.",
  "If I probably didn't have tattoos, or if I probably didn't bleach my hair, or if I probably didn't wear blue jeans and a T-shirt to fancy things, if I didn't do things that make me look like someone who's whacked out of their mind, it'd probably be different. But then again, that's how I wanna dress.",
  "I'm like anybody else. You get enough, you can get beat up. You can get hurt. You can get frustrated. You can get demoralized.",
  "I cannot get enough farro.",
  "I'm gonna open a small restaurant on the beach in Mexico. We're only gonna have a few tables, and we're only gonna cook what's fresh that day. We're gonna get back to the basics... Real food for real people.",
  "People get a little bolder and more wild in summer. You've got things going on kabobs, things cooking on the bone. There's something about standing over a grill or outside with the family that inspires us.",
  "People are very phobic about fish. And if they do cook fish, they fry it, which kills all the flavor.",
  "If you're feeling adventurous, grill up some marinated octopus. It's so healthy.",
  "I'm a big hiker, and I like boxing. I mean, I love a good burger, but I keep things in moderation.",
  "The men and women in the Armed Forces, that's what I always think about and what I teach my kids about. We're getting ready to sit down at the table and have Thanksgiving, and there's people that are not with their families.",
  "One of my good buddies is Marcel Reece with the Raiders. He's a big 'Triple-D' fan; he's a big food fan.",
  "One of my good buddies is Steve Hutchinson. He used to play for the Vikings, and he's also been on 'Triple-D.'",
  "Look, the fame rocket is only on the upward trajectory for a limited time.",
  "A lot of people who like sushi don't really like raw fish or seaweed.",
  "I would ride my horse to school.",
  "I love everything from Enya to Pantera.",
  "As soon as you wanna take away the flavor of anything, just fry it."
];

document.addEventListener("DOMContentLoaded", function() {
  // Some people are just born to cook and talk.
  var $appeal = document.getElementById('fieri_quote');
  var textFitOptions = {
    maxFontSize: 16,
    multiLine: true
  }
  textFitIt();

  setInterval(function() {
    takeMeToFlavorTown(flavors[Math.floor(Math.random() * flavors.length)]);
  }, 5000);

  function takeMeToFlavorTown(msg) {
    $appeal.className = "animating";
    setTimeout(function() {
      $appeal.innerHTML = msg;
      textFitIt();
    }, 500);
    setTimeout(function() {
      $appeal.className = '';
    }, 1000);
  }

  function textFitIt() {
    var textFitOptions = {
      maxFontSize: Math.max(16, Math.floor(window.innerWidth / 50)),
      multiLine: true
    }
    requestAnimationFrame(function() {
      window.textFit($appeal, textFitOptions);
    });
  }
});
